name: ItemTrader
version: ${project.version}
main: com.gmail.supergame314.itemtrader.ItemTrader
api-version: 1.19
authors: [Super__Game]
commands:
  trade:
    permission: itemTrader.canTrade
permissions:
  itemTrader.canTrade:
    default: true
  itemTrader.aboutPermission:
    default: op